version: '3'

services:
  wordpress:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    container_name: "${COMPOSE_PROJECT_NAME}-wordpress"
    mem_limit: 262144000
    restart: "always"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - database
    networks:
      wordpress_net:
        ipv4_address: 10.42.50.10

  wordpress-cli:
    image: wordpress:cli
    container_name: "${COMPOSE_PROJECT_NAME}-wordpress-cli"
    mem_limit: 262144000
    restart: "always"
    volumes:
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - database
      - wordpress
    networks:
      wordpress_net:
        ipv4_address: 10.42.50.11

  phpmyadmin:
    image: phpmyadmin:latest  # https://hub.docker.com/_/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    mem_limit: 262144000
    restart: always
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: database
      PMA_PORT: 3306
      #PMA_USER: root
      #PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
      - "${HOST_MACHINE_PMA_SECURE_PORT}:443"
    volumes:
     - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      database:
        condition: service_healthy
    networks:
      wordpress_net:
        ipv4_address: 10.42.50.12

  database:
    image: mysql:8 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    # platform: linux/x86_64  # Uncomment if your machine is running on arm (ex: Apple Silicon processor)
    container_name: "${COMPOSE_PROJECT_NAME}-mysql"
    mem_limit: 524288000
    restart: "always"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: >
        mysqladmin -h 'localhost' -u 'root' -p"$MYSQL_ROOT_PASSWORD" ping
      interval: 10s
      timeout: 15s
      start_period: 60s
      retries: 5
    networks:
      wordpress_net:
        ipv4_address: 10.42.50.13

volumes:
  db_data:

networks:
  wordpress_net:
    name: wordpress_net_${COMPOSE_PROJECT_NAME}
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-wp-net
    ipam:
      driver: default
      config:
        - subnet: 10.42.50.0/24
          ip_range: 10.42.50.0/24
          gateway: 10.42.50.1